In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelBinarizer

pizza = {"Diameter": [11, 14, 15, 17, 18],
         "Daging_Sapi": [0, 1, 1, 1, 1],
         "Toping": [0, 1, 0, 0, 1],
         "Harga": [21, 24, 25, 28, 32]}
pizza_df = pd.DataFrame(pizza)
pizza_df

Diameter  Daging_Sapi  Toping  Harga
0        11            0       0     21
1        14            1       1     24
2        15            1       0     25
3        17            1       0     28
4        18            1       1     32

# Trainset

In [ ]:
X_train = np.array(pizza_df[['Diameter',	'Daging_Sapi', 'Toping']])
y_train = np.array(pizza_df['Harga'])

print(f"X_train: \n{X_train}\n")
print(f"y_train: \n{y_train}")

X_train: 
[[11  0  0]
 [14  1  1]
 [15  1  0]
 [17  1  0]
 [18  1  1]]

y_train: 
[21 24 25 28 32]


# TestSet

In [ ]:
X_test = np.array(pizza_df[['Diameter',	'Daging_Sapi', 'Toping']])
y_test = np.array(pizza_df['Harga'])

print(f"X_test: \n{X_test}\n")
print(f"y_test: \n{y_test}")

X_test: 
[[11  0  0]
 [14  1  1]
 [15  1  0]
 [17  1  0]
 [18  1  1]]

y_test: 
[21 24 25 28 32]


In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f"r_squared: {r2_score(y_test, y_pred)}")

r_squared: 0.9942857142857143
